#!/bin/sh
# postflight

echo "Running postflight"

defaults write com.apple.loginwindow LoginHook /Library/StartupItems/DoubleCommand/login.command

chown=/usr/sbin/chown
chmod=/bin/chmod
dist=/Library/StartupItems/DoubleCommand
${chown} -R root:wheel ${dist}
${chmod} -R +Xr ${dist}

tmppref=/tmp/DoubleCommand.pref
dcpref=/Library/StartupItems/DoubleCommand/DoubleCommand.pref

if [ -e "$tmppref" ]; then
	mv -f "$tmppref" "$dcpref" 
fi

# pause for a sec in case this next one crashes
sleep 1

# I like the idea of using the kext id directly, seems cleaner
# than basing this purely on the filesystem location of the on disk kext.
kext_ids="com.baltaks.kext.DoubleCommand"
kext_ids="$kext_ids com.baltaks.driver.DoubleCommand"
kextunload=/sbin/kextunload
kextstat=/usr/sbin/kextstat

for k in ${kext_ids}; do
	kexts=$(${kextstat} -l -b ${k} | wc -l)
	if [ ${kexts} -gt 0 ]; then
		${kextunload} -b ${k}
	fi
done

#dcscript=/Library/StartupItems/DoubleCommand/DoubleCommand

#if [ -e "$dcscript" ]; then
#    $dcscript stop
#fi

touch /System/Library/Extensions

dcscript=/Library/StartupItems/DoubleCommand/DoubleCommand

if [ -e "$dcscript" ]; then
    $dcscript start
fi
