#!/bin/sh
# postflight

chown=/bin/chown
chmod=/bin/chmod
kext=/Library/StartupItems/DoubleCommand/DoubleCommand.kext
${chown} -R root:wheel ${kext}
${chmod} -R +Xr ${kext}

tmppref=/tmp/DoubleCommand.pref
dcpref=/Library/StartupItems/DoubleCommand/DoubleCommand.pref

if [ -e "$tmppref" ]; then
	mv -f "$tmppref" "$dcpref" 
fi

dcscript=/Library/StartupItems/DoubleCommand/DoubleCommand

if [ -e "$dcscript" ]; then
    $dcscript start
fi
