#!/bin/sh
# preflight

echo "Running preflight"

dcpref=/Library/StartupItems/DoubleCommand/DoubleCommand.pref

if [ -e ${dcpref} ]; then
	cp -f ${dcpref} /tmp/DoubleCommand.pref
fi

dcfolder=/Library/StartupItems/DoubleCommand

if [ -e ${dcfolder} ]; then
	echo removing ${dcfolder}
	rm -fr ${dcfolder}
fi

dccrashed=/var/tmp/DoubleCommand.crashed

if [ -e ${dccrashed} ]; then
	echo removing ${dccrashed}
	rm -f ${dccrashed}
fi

pref=/Library/PreferencePanes/DoubleCommandPreferences.prefPane

if [ -e ${pref} ]; then
	echo removing ${pref}
	rm -rf ${pref}
fi

exit 0
