#!/bin/sh

# tool to write the prefs value to the global prefs file
# will be called from the prefs pane
# Written 2003_1004 by Christian Nadolle

double_install_dir=/Library/StartupItems/DoubleCommand/
global_prefs=$double_install_dir/DoubleCommand.pref

config_value="$1";

echo $config_value > $global_prefs

